stages:
  - build

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/okinta/stack-algatrader:latest .
    - docker push registry.gitlab.com/okinta/stack-algatrader:latest
  only:
    - master
