name: Run tests and publish

on:
  - push
  - repository_dispatch

jobs:
  publish:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
          password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
          registry: registry.gitlab.com
          repository: okinta/stack-algatrader
          tags: latest
